{
  "props": {
    "singleton": true
  },
  "components": {
    "ringsound": {
      "type": "script\\MediaPlayerScript",
      "x": 32,
      "y": 352,
      "props": {
        "loop": true,
        "autoplay": false,
        "volume": "1.0",
        "balance": "0.0",
        "rate": "1.0"
      }
    },
    "errorsound": {
      "type": "script\\MediaPlayerScript",
      "x": 32,
      "y": 272,
      "props": {
        "autoplay": false,
        "volume": "1.0",
        "balance": "0.0",
        "rate": "1.0"
      }
    },
    "donesound": {
      "type": "script\\MediaPlayerScript",
      "x": 32,
      "y": 192,
      "props": {
        "autoplay": false,
        "volume": "1.0",
        "balance": "0.0",
        "rate": "1.0"
      }
    },
    "masicplay": {
      "type": "script\\MediaPlayerScript",
      "x": 128,
      "y": 112,
      "props": {
        "loop": true,
        "autoplay": false,
        "volume": "1.0",
        "balance": "0.0",
        "rate": "1.0"
      }
    },
    "dtmfsound": {
      "type": "script\\MediaPlayerScript",
      "x": 32,
      "y": 112,
      "props": {
        "loop": true,
        "autoplay": false,
        "volume": "1.0",
        "balance": "0.0",
        "rate": "1.0"
      }
    },
    "podcastplay": {
      "type": "script\\MediaPlayerScript",
      "x": 128,
      "y": 32,
      "props": {
        "autoplay": false,
        "volume": "1.0",
        "balance": "0.0",
        "rate": "1.0"
      }
    },
    "touchsound": {
      "type": "script\\MediaPlayerScript",
      "x": 32,
      "y": 32,
      "props": {
        "autoplay": false,
        "volume": "1.0",
        "balance": "0.0",
        "rate": "1.0"
      }
    }
  }
}