{
  "props": {
    "singleton": true
  },
  "components": {
    "clickScript": {
      "type": "script\\MacroScript",
      "x": 32,
      "y": 352,
      "props": {}
    },
    "hoverScript": {
      "type": "script\\MacroScript",
      "x": 32,
      "y": 272,
      "props": {}
    },
    "clickPlayer": {
      "type": "script\\MediaPlayerScript",
      "x": 32,
      "y": 192,
      "props": {
        "autoplay": false,
        "volume": 1.0,
        "balance": "0.0",
        "rate": "1.0"
      }
    },
    "hoverPlayer": {
      "type": "script\\MediaPlayerScript",
      "x": 32,
      "y": 112,
      "props": {
        "autoplay": false,
        "volume": 1.0,
        "balance": "0.0",
        "rate": "1.0"
      }
    },
    "loopPlayer": {
      "type": "script\\MediaPlayerScript",
      "x": 32,
      "y": 32,
      "props": {
        "loop": true,
        "autoplay": "1",
        "volume": 1.0,
        "balance": "0.0",
        "rate": 1.0
      }
    }
  }
}